name: CI Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install requests python-dateutil dacite
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Save Cookies Into cookies.json
      id: create-cookies
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "cookies.json"
        json: ${{ secrets.COOKIES_JSON }}
        dir: 'soundcld/'

    - name: Save Data Into data.json
      id: create-data
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "data.json"
        json: ${{ secrets.DATA_JSON }}
        dir: 'soundcld/'

    - name: Lint with flake8
      run: |
        flake8 soundcld/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 soundcld/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        python -m pytest
